language: node_js
node_js:
  - "6"
before_install:
  npm i -g prez
script: npm start
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
